CREATE TABLE IF NOT EXISTS public."USER_FAVORITES" (
  "FAVORITE_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
  "USER_ID" uuid NOT NULL,
  "PRODUCT_ID" uuid NOT NULL,
  "CREATED_AT" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "USER_FAVORITES_pkey" PRIMARY KEY ("FAVORITE_ID"),
  CONSTRAINT "USER_FAVORITES_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES public."PROFILE"("USER_ID") ON DELETE CASCADE,
  CONSTRAINT "USER_FAVORITES_PRODUCT_ID_fkey" FOREIGN KEY ("PRODUCT_ID") REFERENCES public."PRODUCT"("PRODUCT_ID") ON DELETE CASCADE,
  CONSTRAINT "USER_FAVORITES_USER_PRODUCT_unique" UNIQUE ("USER_ID", "PRODUCT_ID")
);

ALTER TABLE public."USER_FAVORITES" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own favorites"
  ON public."USER_FAVORITES" FOR SELECT
  USING (auth.uid() = "USER_ID");

CREATE POLICY "Users can insert own favorites"
  ON public."USER_FAVORITES" FOR INSERT
  WITH CHECK (auth.uid() = "USER_ID");

CREATE POLICY "Users can delete own favorites"
  ON public."USER_FAVORITES" FOR DELETE
  USING (auth.uid() = "USER_ID");
